import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const fallback = [
 { title:'Dawn, Unfolding', artist:'Amara Okafor', location:'Lagos, Nigeria', price:2400, medium:'Mixed media', year:2024, image:'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=85' },
 { title:'Quiet Geometry', artist:'Sora Kim', location:'Seoul, Korea', price:1800, medium:'Acrylic on canvas', year:2023, image:'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=900&q=85' },
 { title:'Red Horizon', artist:'Luca Bianchi', location:'Milan, Italy', price:3100, medium:'Oil on linen', year:2024, image:'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=900&q=85' }
];
function App() {
 const [works,setWorks] = useState(fallback); const [menu,setMenu] = useState(false);
 useEffect(() => { fetch('/api/artworks').then(r=>r.json()).then(setWorks).catch(()=>{}); const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.15}); document.querySelectorAll('.reveal').forEach(e=>observer.observe(e)); return ()=>observer.disconnect(); },[]);
 return <main>
  <nav><a className="brand" href="/preview.html">ARTISPHERE<span>®</span></a><div className={'links '+(menu?'open':'')}><a href="/collection.html">Discover</a><a href="/artists.html">Artists</a><a href="/sell.html">Sell art</a></div><button className="menu" onClick={()=>setMenu(!menu)} aria-label="menu">☰</button><a className="pill" href="/join.html">Join the circle <i>↗</i></a></nav>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">A global canvas for original art</p><h1>Art that<br/><em>moves</em> you.</h1><p className="lede">Meet the makers reshaping the world, one singular work at a time.</p><div className="actions"><a className="button" href="/collection.html">Explore artworks <span>↘</span></a><a className="text-link" href="/sell.html">Sell your art <b>→</b></a></div></div><div className="orbit-scene" aria-label="abstract floating artwork"><div className="halo"></div><div className="orb orb-one"></div><div className="orb orb-two"></div><a className="art-card" href="/artwork.html"><img src="https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=85"/><div className="card-caption"><span>FEATURED WORK</span><strong>Dawn, Unfolding</strong></div></a><div className="scribble">✳</div></div><div className="scroll">SCROLL TO EXPLORE <span>↓</span></div></section>
  <section className="statement reveal"><p className="eyebrow">WHAT WE BELIEVE</p><h2>Art belongs <em>everywhere.</em><br/>So do artists.</h2><p>Artisphere makes it feel less like a transaction and more like a meaningful encounter—connecting collectors with artists from every corner of the world.</p></section>
  <section className="collection" id="discover"><div className="section-top reveal"><div><p className="eyebrow">CURATED THIS WEEK</p><h2>Fresh from<br/><em>the studio.</em></h2></div><a className="round-link" href="#all">View all <span>→</span></a></div><div className="art-grid">{works.slice(0,3).map((work,i)=><article className={'work reveal work-'+i} key={work.title}><div className="image-wrap"><img src={work.image} alt={work.title}/><button>♡</button></div><div className="work-info"><div><h3>{work.title}</h3><p>{work.artist} · {work.location}</p></div><strong>${work.price.toLocaleString()}</strong></div><small>{work.medium} · {work.year}</small></article>)}</div></section>
  <section className="artist-banner" id="artists"><div className="portrait"><img src="https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1000&q=85" alt="Artist in a studio"/></div><div className="artist-copy reveal"><p className="eyebrow">MEET THE ARTISTS</p><h2>Created with<br/><em>a point of view.</em></h2><p>Discover bold new voices, established masters, and the stories behind the work.</p><a className="button light" href="#artists">Meet the artists <span>↗</span></a></div><div className="star">✦</div></section>
  <section className="sell reveal" id="sell"><p className="eyebrow">FOR ARTISTS, BY ART LOVERS</p><h2>Your work has<br/><em>somewhere to go.</em></h2><p>Join a worldwide community that sees the value in what you make.</p><a className="button" href="mailto:hello@artisphere.example">Start selling <span>↗</span></a></section>
  <footer><a className="brand" href="#top">ARTISPHERE<span>®</span></a><p>Original art, shared with the world.</p><div><a href="#discover">Discover</a><a href="#sell">For artists</a><a href="#top">Instagram</a></div></footer>
 </main>
}
createRoot(document.getElementById('root')).render(<App/>);
